### ISSUE TITLE
Not working on Sierra

### ISSUE THREAD

**Issue by manishie** [isometry/alfredworkflows#10]
Great workflow (ssh), thanks!  It just stopped working after I upgraded to Sierra.

**Comment by isometry** [comment]
Which version of the workflow do you have installed (v1.3 is current), and what version of Alfred (2.x or 3.x)?

**Comment by manishie** [comment]
Hi, I'm so sorry, I thought I had updated this workflow but I guess I hadn't.  I just updated with the latest version of yours and it's working again.  thanks!

**Comment by isometry** [comment]
Excellent. Please to hear the update fixed it.
NB: I'll be releasing an updated version 2.0, optimised for Alfred 3 and
with additional configuration options, soon.

**Comment by manishie** [comment]
Looking forward to it!  thx again.

mkm

**Comment by isometry** [comment]
The updated workflow is now available [here](https://github.com/isometry/alfred-ssh/releases/latest)

**Comment by manishie** [comment]
thank so much!  seems to work great.
