### ISSUE TITLE
Wildcard cases on .ssh/config

### ISSUE THREAD

**Issue by bondezbond** [isometry/alfredworkflows#5]
Is there anyway we can support wildcard hosts? For instance I have an ssh config

```bash
Host *u
Username testuser
IdentityFile ~/path/to/pem

Host *r
Username root
IdentityFile ~/path/to/pem

Host machine-1*
Hostname my.hostname.com
```

This gives me the ability to login is as two different users
ssh machine-1u
ssh machine-1r

**Comment by isometry** [comment]
I can't see a sane way to handle wildcards, but I'm open to suggestions. Do you realise that you can include a username in the command? e.g. "ssh root@m1" => "ssh root@machine-1"

**Comment by bondezbond** [comment]
Yeah but it doesn't pick the IdentityFile

**Comment by isometry** [comment]
How about using the `Match User` directive rather than `Host`? e.g.:
```
Match User testuser
IdentityFile ~/path/to/pem
```

**Comment by isometry** [comment]
Hmm. I can't actually get user aliases to work (i.e. `Match user t` => `User testuser`), but I think that IdentityFile override should still work…

**Comment by bondezbond** [comment]
I'll try that out and see how it goes. Does limit the options if the same user is used with a different identity file. Thanks for the advice
