### ISSUE TITLE
Not work on Alfred 3

### ISSUE THREAD

**Issue by kecinzer** [isometry/alfredworkflows#6]
Hello.
I'm using latest beta version of Alfred 3 (as megasupporter) and this workflow no longer works.
Can you please look at it?
When I type "ssh " and then start to typing system, Alfred help text changed to "Search Google for...".

**Comment by isometry** [comment]
I've just upgrade to Alfred 3 myself, and the workflow continued working without issue post-upgrade. Can you confirm that you have the latest version installed, and that you've tried removing and reinstalling?

**Comment by isometry** [comment]
Can you confirm that the "Script Filter" object *hasn't* somehow flipped from `/usr/bin/python with input as {query}` to `/usr/bin/python with input as argv` as part of the upgrade?

**Comment by isometry** [comment]
I believe this issue has now been resolved with 7799e6d79d0d2659994b7fff3242dcfbd4000247.
