### ISSUE TITLE
Prioritize ssh config over known_hosts

### ISSUE THREAD

**Issue by macbookandrew** [isometry/alfredworkflows#7]
Is it possible to prioritize matches from `~/.ssh/config` over matches from `~/.ssh/known_hosts`, on the theory that if I have them set up in my config, I’m more likely to use them than a host in my history?

I’d take a stab at it myself, but I have 0 experience with Python.

**Comment by isometry** [comment]
Prioritisation is mostly left to Alfred, and is determined by usage: if you frequently use a particular application to select a particular host (e.g. using Cmd-Number to select something other than the top hit), Alfred will learn and filter that result to the top in future.

**Comment by macbookandrew** [comment]
Thanks; I knew Alfred prioritized things somewhat base on usage, but for some reason I hadn’t noticed that behavior with SSH hosts.

**Comment by isometry** [comment]
No problem. The workflow does prioritise initially based on proximity to the abbreviation you type, but Alfred gets to override that so adapting to actual usage :-)
